#! /bin/bash
# Copyright 2013 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run initialization code the first time this image boots on a given instance.

"$PREFIX/usr/share/google/is-first-boot-for-instance" || exit

#####################################################################
# We are booting this instance for the first time.
#
# If the instance hasn't changed, we have now exited this script.
# Since the instance changed, we have to do a bunch of work.
#####################################################################

declare -r INSTANCE_ID="$(cat "$PREFIX/var/lib/google/vm-instance-id")"

function log() {
  if [[ -x ${PREFIX}/usr/bin/logger ]]; then
    echo $* | ${PREFIX}/usr/bin/logger -t first-boot -p auth.info
  else
    echo $* >&2
  fi
}

log "Running first-boot"

# Regenerate host keys for ssh.
[[ -x "$PREFIX}/usr/share/google/regenerate-host-keys" ]] &&
  "$PREFIX/usr/share/google/regenerate-host-keys"

# Make a per-instance data directory.
mkdir -p "$PREFIX/var/lib/google/per-instance/$INSTANCE_ID"
